### PR TITLE
async/await and multiple db connections

### LINKED ISSUE #11: Support multiple db connections
It would be great to support multiple db connections.

### LINKED ISSUE #24: Migrate callbacks patterns to async/await
It's time for the big change. 😬

### LINKED ISSUE #27: MongoClient.connect function incompatible with Node MongoDB 3.6 driver
Hello!

The MongoClient.connect method in the MongoDB 3.6 driver has changed. See the [changelog](https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md) for more info, beginning with "MongoClient.connect works as expected but it returns...". MongoClient.connect no longer returns the database, but an instance of MongoClient. 

So the [connect method](https://github.com/jedireza/mongo-models/blob/master/index.js#L30) will have to be refactored to something like the following: 

```
static connect(uri, dbName options, callback) { 
        Mongodb.MongoClient.connect(uri, options, (err, client) => {
            if (err) {
                return callback(err);
            }
            MongoModels.db = client.db(dbName);
            callback(null, db);
        });
 }
```
Or maybe the dbName could be included in the options object.

Happy to do a pull request.

### PR DESCRIPTION
**Pull request by jedireza**
This PR brings us into the `async`/`await` world.

This PR also adds support for multiple db connections via an optional named connection API. So if you only have one connection, or use the default, you connect and call functions like normal:  (Ex: `Model.count({})`). And if you have multiple connections, you can specify the name of the connection when connecting and then use the name via the new `with(...)` method: (Ex: `Model.with('named').count({})`).

Resolves #11 
Resolves #24 
Resolves #27 

TODO:

 - [X] Do the work
 - [X] Update README.md
 - [X] Add example app
 - [X] Update the API docs
 - [x] Document breaking changes
    - [x] The minimum supported driver is `mongodb@3.x.x`
    - [x] Callbacks are gone everything is `async`/`await`.
    - [x] The property `constructWithSchema` has been removed. The default behavior is to always construct with the schema.
    - [x] The constructor will throw if there was a validation error.
    - [x] The property `collection` has been renamed to `collectionName`.
    - [x] The `connect` method now expects a `connection` object with keys `uri` and `db`.
    - [x] The `pagedFind` method no longer accepts the `fields` or `sort` arguments. Use the `options` argument instead.

### CODE REVIEW

**Comment by jedireza** [comment]
This is ready for a final review if anyone is interested. I'll probably merge this evening if I don't hear anything. As always please file issues if you find anything that needs to be corrected.

**Comment by dwmkerr** [comment]
This is awesome, will try it right now on one of my projects and see how it goes, will update shortly :)

**Comment by dwmkerr** [comment]
Looking good! The only suggestion I would make would be to put the details of how `MongoModels.connect` works in the README, initially I was just passing my connection string (as I would for `MongoClient.connect`) but the connection string needs to be in an object, along with the DB name. Maybe something like:

```

### Connecting to MongoDB

MongoModels uses the standard [`MongoClient.connect`](https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html) function to establish a connection. However, to support connections to multiple databases, the database name must also be provided when connecting:

```js
const db = await MongoModels.connect({ uri: connectionString, db: dbName });
```

**Comment by jedireza** [comment]
Thanks for test driving @dwmkerr.

> However, to support connections to multiple databases, the database name must also be provided when connecting:

We need the db name now because ` MongoClient.connect` no longer returns a `MongoDB.Db`, rather it returns a `MongoDB.MongoClient`. And in order to get a DB instance from the client, you `client.db(dbName)`.

Did you have a chance to review the API docs? You can see a preview of the new docs here: https://github.com/jedireza/mongo-models/blob/async-await-and-multiple-connections/API.md

**Comment by dwmkerr** [comment]
Yep the API docs look great, the only thing I was wondering is whether the same info in a cut down form should be on the main README, as almost the first thing anyone is going to do is build a model then connect. If they've got the info on the README they'll get started quickly then can refer to the API docs for details as needed, but it is not a big thing at all!

**Comment by jedireza** [comment]
Thanks for mentioning this. I've included the same code that's in the example app on the readme. Good call.

**Comment by dwmkerr** [comment]
Looks great! Looking forward to having this, will let me eliminate a load of extra code I've got 👍

**Pull request merged**
