### PR TITLE
Update for Node MongoDB driver v3+

### LINKED ISSUE #27: MongoClient.connect function incompatible with Node MongoDB 3.6 driver
Hello!

The MongoClient.connect method in the MongoDB 3.6 driver has changed. See the [changelog](https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md) for more info, beginning with "MongoClient.connect works as expected but it returns...". MongoClient.connect no longer returns the database, but an instance of MongoClient. 

So the [connect method](https://github.com/jedireza/mongo-models/blob/master/index.js#L30) will have to be refactored to something like the following: 

```
static connect(uri, dbName options, callback) { 
        Mongodb.MongoClient.connect(uri, options, (err, client) => {
            if (err) {
                return callback(err);
            }
            MongoModels.db = client.db(dbName);
            callback(null, db);
        });
 }
```
Or maybe the dbName could be included in the options object.

Happy to do a pull request.

### PR DESCRIPTION
**Pull request by andyfry01**
This PR updates the package to accommodate breaking changes introduced in the Node MongoDB driver v3+. 

**Changes**: 
- Changed the connection API for MongoModels#connect. Previously it took a mongodb URI string as its first argument, and it now accepts a connection object consisting of two properties: 
1.  a mongodb uri (e.g. `mongodb://localhost:27017`)
2. the name of the database being connected to (e.g. `test_database`)

- Updated API.md, README.md, and test/index.js to accommodate the API change. 

This resolves #27

### CODE REVIEW

**Comment by jedireza** [comment]
Will you be able to resolve the merge conflicts?

**Comment by jedireza** [comment]
I was able to grok your PR and just pushed an update to #25 to support the mongodb driver v3.x.

**Comment by jedireza** [comment]
I'm going to close this PR for now. The rest of the work is with documenting the changes. If you have time for a code review of #25 that would be very helpful. Thanks again for getting involved.

**Comment by andyfry01** [comment]
As in just do a pull of the [async-await branch](https://github.com/jedireza/mongo-models/tree/async-await-and-multiple-connections) and do a general code review? I could do that. If you'd like some documentation updates I can do that too

**Comment by jedireza** [comment]
https://github.com/jedireza/mongo-models/pull/25 is ready for a final review. I've updated the docs.

**Pull request closed without merging**
